# Generated by Django 5.1 on 2024-08-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
