# Generated by Django 5.1 on 2024-08-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='place',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_alma.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app_alma.category'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='app_alma.student'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='app_alma.category'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='coach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='app_alma.coach'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='app_alma.student'),
        ),
    ]
