# Generated by Django 5.1 on 2024-08-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='coach_id',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='TrainingSession',
        ),
    ]
