# Generated by Django 5.1 on 2024-08-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alma', '0002_remove_trainingsession_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_id',
            new_name='student',
        ),
    ]
