# Generated by Django 5.1 on 2024-08-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alma', '0003_rename_student_id_payment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Up to date', 'Up To Date'), ('Pending', 'Pending'), ('Late', 'Late')], default='Up to date', max_length=20),
        ),
    ]
