# Generated by Django 5.1 on 2024-08-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alma', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_status',
        ),
    ]
