# Generated by Django 5.1 on 2024-08-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alma', '0005_remove_student_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_alma.student'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_alma.student'),
        ),
    ]
